
version: '3.7'
services:
    komidb:
      build: docker-script/postgre
      container_name: komidb
      image: fransmzh/komi-db:1.7
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=komidb
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5433:5432'
      volumes: 
        - komidb:/var/lib/postgresql/data
      networks: 
        - docnet

    inbound:
      build: bifast-inbound
      image: fransmzh/komi-inbound:1.7
      container_name: komi-inbound
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9001"
      ports: 
        - "9001:9001"
      environment: 
        - SPRING_DATASOURCE_URL=jdbc:postgresql://komidb:5432/komidb 
        - SPRING.DATASOURCE.USERNAME=postgres 
        - SPRING.DATASOURCE.PASSWORD=postgres 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - LOGGING.FILE.NAME=/home/logs/komi-inbound.log
        - KOMI.BANKCODE=SIHBIDJ1
        - KOMI.COREBANK-URL=localhost:9003/services/cb
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/inbound:/home/logs
      networks: 
        - docnet

    outbound:
      build: bifast-outbound
      image: fransmzh/komi-outbound:1.7
      container_name: komi-outbound
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9002"
      ports: 
        - "9002:9002"
      environment: 
        - KOMI.CICONNECTOR-URL=komi-mock:9006/mock/cihub
        - KOMI.BANKCODE=SIHBIDJ1
        - KOMI.BICODE=INDOIDJA
        - KOMI.INBOUND-URL=komi-inbound:9001/services/api/enquiry
        - LOGGING.FILE.NAME=/home/logs/komi-outbound.log
        - LOGGING.LEVEL.BIFAST.OUTBOUND=DEBUG
        - SPRING_DATASOURCE_URL=jdbc:postgresql://komidb:5432/komidb 
        - SPRING.DATASOURCE.USERNAME=postgres 
        - SPRING.DATASOURCE.PASSWORD=postgres 
        - SPRING.MAIN.BANNER-MODE=OFF 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/outbound:/home/logs
      networks: 
        - docnet

    mock:
      build: bifast-mock
      container_name: komi-mock
      image: fransmzh/komi-mock:1.7
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9006"
      ports: 
        - "9006:9006"
      environment: 
        - LOGGING.FILE.NAME=/home/logs/komi-mock.log
        - BIFAST.INBOUND-LOG-FOLDER=/home/logs
        - KOMI.INBOUND-URL=komi-inbound:9001/services/api
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/mock:/home/logs
      networks: 
        - docnet
    
volumes:
  komidb: {}

networks: 
  docnet: {}
