
version: '3.7'
services:
    komidb:
      build: komi-db
      image: fransmzh/komi-db:1.9
      container_name: komi-db
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=komidb
        - TZ=Asia/Jakarta
      expose: 
        - "5432"
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5433:5432'
      volumes: 
        - komidb:/var/lib/postgresql/data
      networks: 
        - docnet

    inbound:
      build: bifast-inbound
      image: fransmzh/komi-inbound:2.3.1
      container_name: komi-inbound
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9001"
      ports: 
        - "9001:9001"
      environment: 
        - SPRING_DATASOURCE_URL=jdbc:postgresql://komidb:5432/komidb 
        - SPRING.DATASOURCE.USERNAME=postgres 
        - SPRING.DATASOURCE.PASSWORD=postgres 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - LOGGING.FILE.NAME=/home/logs/komi-inbound.log
        - KOMI.BANKCODE=SIHBIDJ1
        - KOMI.URL.COREBANK=http://172.18.0.1:9007/api/corebank
        - KOMI.URL.PORTALAPI=http://172.18.0.1:9006/mock
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/inbound:/home/logs
      networks: 
        - docnet

    outbound:
      build: bifast-outbound
      image: fransmzh/komi-outbound:2.3.2
      container_name: komi-outbound
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9002"
      ports: 
        - "9002:9002"
      environment: 
        - KOMI.URL.CICONNECTOR=http://172.18.0.1:9006/mock/cihub
        - KOMI.URL.COREBANK=172.18.0.1:9007/api/corebank
        - KOMI.URL.ISOADAPTER=http://172.18.0.1:9006/mock/adapter
        - KOMI.URL.PORTALAPI=http://172.18.0.1:9006/mock
        - KOMI.URL.INBOUND=172.18.0.1:9001
        - KOMI.BANKCODE=SIHBIDJ1
        - KOMI.BICODE=INDOIDJA
        - LOGGING.FILE.NAME=/home/logs/komi-outbound.log
        - LOGGING.LEVEL.BIFAST.OUTBOUND=DEBUG
        - SPRING_DATASOURCE_URL=jdbc:postgresql://komidb:5432/komidb 
        - SPRING.DATASOURCE.USERNAME=postgres 
        - SPRING.DATASOURCE.PASSWORD=postgres 
        - SPRING.MAIN.BANNER-MODE=OFF 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/outbound:/home/logs
      networks: 
        - docnet

    mock:
      build: bifast-mock
      container_name: komi-mock
      image: fransmzh/komi-mock:2.3.1
      restart: always
      depends_on: 
        - komidb
      expose: 
        - "9006"
      ports: 
        - "9006:9006"
      environment: 
        - LOGGING.FILE.NAME=/home/logs/komi-mock.log
        - BIFAST.INBOUND-LOG-FOLDER=/home/logs
        - KOMI.INBOUND-URL=172.18.0.1:9001/komi-inbound/json/service
        - KOMI.TIMEOUT-CT=50000
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/mock:/home/logs
      networks: 
        - docnet
    
    mock-cb:
      build: corebankiface
      container_name: mock-cb
      image: fransmzh/mock-cb:1.0
      restart: always
      expose: 
        - "9007"
      ports: 
        - "9007:9007"
      environment: 
        - TZ=Asia/Jakarta
      networks: 
        - docnet

    cb-adam:
      container_name: mock-cb
      image: fransmzh/mock-cb:adam3
      depends_on: 
        - komidb
      expose: 
        - "9007"
      ports: 
        - "9007:9007"
      environment: 
        - LOGGING.FILE.NAME=/home/logs/komi-mock.log
        - SPRING_DATASOURCE_URL=jdbc:postgresql://komidb:5432/komidb 
        - SPRING.DATASOURCE.USERNAME=postgres 
        - SPRING.DATASOURCE.PASSWORD=postgres 
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - TZ=Asia/Jakarta
      volumes: 
        - /home/fransdm/workspace/bifast-log/mock:/home/logs
      networks: 
        - docnet

volumes:
  komidb: {}

networks: 
  docnet: {}
